import Head from 'next/head'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <nav className={styles.nav}>
      </nav>
      <main className={styles.main}>
        
        <section className={styles.section} id={styles.landing}>
          <h1 className={styles.title}>
            Algo-trading framework for <a href="https://www.merriam-webster.com/dictionary/tinker">tinkers</a> 🛠️
          </h1>
          <p>
            Harvest is a robust, flexible Python framework to 
            easily trade a wide variety of assets.
          </p>
          <button>
            Temp
          </button>
        </section>
        <section className={styles.section}>
          <div className={styles.col_card}>
            <img src="https://via.placeholder.com/512"></img>
            <h2>Beginners Welcome</h2>
            <p>
            If you’re new to trading, coding, or both - no worries, 
            Harvest was specifically designed so beginners in 
            both trading and coding can easily get started. 
            </p>
          </div>
          <div className={styles.col_card}>
            <img src="https://via.placeholder.com/512"></img>   
            <h2>Exotic Features</h2>
            <p>
            Harvest’s philosophy is that rather than 
            absolute stability, it’s better to support experimental, 
            exciting features while maintaining a practical level 
            of reliability. 
            </p>
          </div>
          <div className={styles.col_card}>
            <img src="https://via.placeholder.com/512"></img>
            <h2>Built to be Modded</h2>
            <p>
            The codebase is designed so developers can easily to add their 
            own code and implement custom features. 
            </p>
          </div>
        </section>
      </main>

      <footer className={styles.footer}>
        
      </footer>
    </div>
  )
}
